"use client";
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useParams } from 'next/navigation';
import { useState } from 'react';
import { CrmShell } from '../../../../components/crm-shell';
import { SafeLink as Link } from '../../../../components/safe-link';
import { QuoteEditor } from '../../../../components/quote-editor';
import { api } from '../../../../lib/api';
import { Opportunity, formatDate } from '../../../../lib/crm';
import { Quote, hasTimeEstimates, timeQuantity, timeEstimateNote, money, toDraft } from '../../../../lib/quotes';
const button = 'rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold disabled:opacity-50';
export default function QuoteDetailPage() {
  const { id } = useParams<{ id: string }>();
  const client = useQueryClient();
  const [editing, setEditing] = useState(false);
  const query = useQuery({ queryKey: ['quote', id], queryFn: () => api<Quote>(`/quotes/${id}`) });
  const opportunities = useQuery({ queryKey: ['opportunities'], queryFn: () => api<Opportunity[]>('/opportunities') });
  const update = (quote: Quote) => { client.setQueryData(['quote', id], quote); client.invalidateQueries({ queryKey: ['quotes'] }); };
  const status = useMutation({ mutationFn: (value: Quote['status']) => api<Quote>(`/quotes/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status: value, version: query.data?.__v }) }), onSuccess: update });
  const duplicate = useMutation({ mutationFn: () => api<Quote>('/quotes', { method: 'POST', body: JSON.stringify({ ...toDraft(query.data!), title: `${query.data!.title.slice(0, 180)} (copy)` }) }), onSuccess: quote => { client.invalidateQueries({ queryKey: ['quotes'] }); window.location.assign(`/opportunities/quotes/${quote._id}`); } });
  const quote = query.data;
  let user: { id: string; role: string } | null = null;
  if (typeof window !== 'undefined') { try { user = JSON.parse(localStorage.getItem('crm_user') || 'null'); } catch { /* Auth gate handles invalid sessions. */ } }
  const canEdit = user && (user.role !== 'salesperson' || quote?.owner === user.id);
  if (!quote) return <CrmShell activePath="/opportunities/quotes"><div className="p-10"><p>{query.isLoading ? 'Loading quote…' : 'Quote could not be loaded.'}</p><Link href="/opportunities/quotes" className="mt-4 block text-indigo-600">Return to quotes</Link></div></CrmShell>;
  return <CrmShell activePath="/opportunities/quotes"><div className="quote-page mx-auto max-w-[1100px] px-4 py-7 md:px-8 md:py-9">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3 print:hidden"><Link href={`/opportunities/quotes?opportunity=${quote.opportunity?._id || ''}`} className="text-sm font-semibold text-indigo-600">← Quotes</Link><div className="flex flex-wrap gap-2">{canEdit && <><button className={button} disabled={duplicate.isPending || !quote.opportunity} onClick={() => duplicate.mutate()}>Duplicate</button>{quote.status === 'draft' && <button className={button} disabled={!opportunities.data} onClick={() => setEditing(true)}>Edit quote</button>}<select aria-label="Quote status" className={button} disabled={status.isPending} value={quote.status} onChange={event => { const value = event.target.value as Quote['status']; if (value !== 'draft' || window.confirm('Reopen this quote as a draft? Duplicate it instead if you want to retain the original version.')) status.mutate(value); }}>{['draft', 'sent', 'accepted', 'declined', 'closed'].map(value => <option key={value} value={value}>{value === 'sent' ? 'Sent (record only)' : value}</option>)}</select></>}<button className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white" onClick={() => { const title = document.title; document.title = `${quote.number} - ${quote.title}`; window.print(); document.title = title; }}>Print / PDF</button></div></div>
    {(status.error || duplicate.error) && <p role="alert" className="mb-4 text-sm text-rose-600 print:hidden">{status.error?.message || duplicate.error?.message}</p>}
    <p className="mb-5 text-xs text-slate-500 print:hidden">Choose “Save as PDF” in the print dialog. Marking a quote sent records its status; it does not email the customer.</p>
    <article className="quote-document rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-12">
      <header className="flex flex-wrap justify-between gap-6 border-b-4 border-indigo-600 pb-7"><div><p className="text-xl font-bold">{quote.sellerName}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-500">{quote.sellerAddress}</p><p className="mt-2 text-sm text-slate-500">{quote.sellerEmail}</p></div><div className="text-right"><p className="text-3xl font-light uppercase tracking-widest text-indigo-950">{hasTimeEstimates(quote.lineItems) ? 'Estimate' : 'Quote'}</p><p className="mt-3 font-bold">{quote.number}</p><p className="mt-1 text-xs uppercase text-slate-500">{quote.status}</p></div></header>
      <section className="mt-8 grid grid-cols-2 gap-6"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Prepared for</p><p className="mt-2 font-bold">{quote.customerName}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-500">{quote.customerAddress}</p><p className="mt-2 text-sm text-slate-500">{quote.customerEmail}</p></div><div className="text-right text-sm"><p>Issued: {formatDate(quote.issueDate)}</p><p className="mt-2">Valid until: {quote.validUntil ? formatDate(quote.validUntil) : 'No expiry specified'}</p><p className="mt-2">Currency: {quote.currency}</p></div></section>
      <h1 className="mt-9 text-2xl font-bold">{quote.title}</h1>{quote.introduction && <p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-600">{quote.introduction}</p>}
      <div className="quote-items mt-8 overflow-x-auto"><table className="w-full min-w-[600px] table-fixed text-left text-sm"><colgroup><col style={{ width: '42%' }} /><col style={{ width: '20%' }} /><col style={{ width: '18%' }} /><col style={{ width: '20%' }} /></colgroup><thead className="border-y border-slate-200 bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Description</th><th className="p-3 text-right">{hasTimeEstimates(quote.lineItems) ? 'Qty / time' : 'Qty'}</th><th className="p-3 text-right">Rate</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{quote.lineItems.map((line, index) => <tr key={index} className="border-b border-slate-100 align-top"><td className="p-3"><p className="mb-1 text-xs font-bold text-indigo-600">{line.section}</p><p className="whitespace-pre-wrap break-words leading-6">{line.description}</p></td><td className="p-3 text-right">{line.pricingType === 'time' ? <span>{timeQuantity(line)}</span> : <>{line.quantity}<span className="block break-words text-xs text-slate-400">{line.unit}</span></>}</td><td className="break-words p-3 text-right">{money(line.rate, quote.currency)}{line.pricingType === 'time' && <span className="block text-xs text-slate-500">/ {line.unit}</span>}</td><td className="break-words p-3 text-right font-semibold">{money(line.amount || 0, quote.currency)}{line.pricingType === 'time' && <span className="block text-xs font-normal text-slate-500">estimated</span>}</td></tr>)}</tbody></table></div>
      <section className="quote-totals mt-6 ml-auto max-w-sm space-y-2 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{money(quote.subtotal, quote.currency)}</span></div><div className="flex justify-between"><span>Discount</span><span>−{money(quote.discount, quote.currency)}</span></div><div className="flex justify-between"><span>VAT ({quote.vatRate}%)</span><span>{money(quote.vatAmount, quote.currency)}</span></div><div className="flex justify-between border-t-2 border-indigo-600 pt-4 text-xl font-bold"><span>{hasTimeEstimates(quote.lineItems) ? 'Estimated total' : 'Total'}</span><span>{money(quote.total, quote.currency)}</span></div></section>
      {hasTimeEstimates(quote.lineItems) && <p className="mt-6 text-sm leading-6 text-slate-600">{timeEstimateNote}</p>}
      {quote.terms && <section className="mt-10 border-t border-slate-200 pt-6"><h2 className="text-sm font-bold">Terms and conditions</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-600">{quote.terms}</p></section>}
      <footer className="mt-12 break-inside-avoid border-t border-slate-100 pt-5 text-xs text-slate-500"><p>{quote.number} · {quote.sellerName}</p><p className="mt-3 leading-5">Created with Studio CRM by WEBtechSupport. Need a CRM for your small or medium-sized business? Get in touch!</p></footer>
    </article>
  </div>{editing && <QuoteEditor quote={quote} opportunities={opportunities.data || []} onClose={() => setEditing(false)} onSaved={saved => { update(saved); setEditing(false); }} />}</CrmShell>;
}
