"use client";

import { keepPreviousData, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDownRight, ArrowUpRight, ChevronLeft, ChevronRight, Plus, ReceiptText, Trash2, WalletCards, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { CrmShell } from "../../components/crm-shell";
import { api } from "../../lib/api";
import { BudgetTransaction, formatDate } from "../../lib/crm";

type BudgetResponse = { items: BudgetTransaction[]; total: number; page: number; pages: number; totals: { income: number; expenses: number; net: number }; categories: string[] };
const money = (value: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" }).format(value || 0);
const today = () => new Date().toISOString().slice(0, 10);
const monthStart = () => `${today().slice(0, 7)}-01`;

export default function BudgetPage() {
  const queryClient = useQueryClient();
  const [scope, setScope] = useState<"personal" | "freelance">("personal");
  const [search, setSearch] = useState("");
  const [debounced, setDebounced] = useState("");
  const [from, setFrom] = useState(monthStart());
  const [to, setTo] = useState(today());
  const [page, setPage] = useState(1);
  const [creating, setCreating] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { setDebounced(search.trim()); setPage(1); }, 250); return () => window.clearTimeout(timer); }, [search]);
  const params = useMemo(() => new URLSearchParams({ scope, page: String(page), limit: "25", search: debounced, from, to }).toString(), [debounced, from, page, scope, to]);
  const query = useQuery({ queryKey: ["budget", params], queryFn: () => api<BudgetResponse>(`/budget?${params}`), placeholderData: keepPreviousData });
  const remove = useMutation({ mutationFn: (transaction: BudgetTransaction) => api<BudgetTransaction>(`/budget/${transaction._id}`, { method: "DELETE" }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["budget"] }) });
  const changeScope = (value: "personal" | "freelance") => { setScope(value); setPage(1); };
  const totals = query.data?.totals;
  const isThisMonth = from === monthStart() && to === today();
  const freelanceNetQuery = useQuery({
    queryKey: ["budget", "freelance-net", from, to],
    queryFn: () => api<BudgetResponse>(`/budget?scope=freelance&page=1&limit=1&from=${from}&to=${to}`),
    enabled: scope === "personal" && isThisMonth,
  });
  const combinedNet = (totals?.net ?? 0) + (freelanceNetQuery.data?.totals.net ?? 0);
  const resetToThisMonth = () => { setFrom(monthStart()); setTo(today()); setPage(1); };

  return <CrmShell activePath="/budget" search={search} onSearch={setSearch}><div className="mx-auto max-w-[1500px] px-4 py-7 md:px-8 md:py-9">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-indigo-600">Finance</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Budget</h1><p className="mt-2 text-sm text-slate-500">Personal and freelance cash-flow in one workspace.</p></div><button onClick={() => setCreating(true)} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17} />Add transaction</button></div>
    <div className="mt-7 flex w-fit rounded-xl bg-slate-100 p-1">{(["personal", "freelance"] as const).map((value) => <button key={value} onClick={() => changeScope(value)} className={`rounded-lg px-4 py-2 text-sm font-semibold capitalize ${scope === value ? "bg-white text-slate-950 shadow-sm" : "text-slate-500"}`}>{value}</button>)}</div>
    <section className={`mt-5 grid gap-4 sm:grid-cols-2 ${scope === "personal" && isThisMonth ? "xl:grid-cols-4" : "xl:grid-cols-3"}`}><Stat icon={ArrowUpRight} label="Income" value={money(totals?.income ?? 0)} tone="emerald" /><Stat icon={ArrowDownRight} label="Expenses" value={money(totals?.expenses ?? 0)} tone="rose" /><Stat icon={WalletCards} label="Net cash-flow" value={money(totals?.net ?? 0)} tone={(totals?.net ?? 0) >= 0 ? "indigo" : "rose"} />{scope === "personal" && isThisMonth && <Stat icon={WalletCards} label="Including freelance" value={money(combinedNet)} tone={combinedNet >= 0 ? "indigo" : "rose"} />}</section>
    <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><DateField label="From" value={from} onChange={(value) => { setFrom(value); setPage(1); }} /><DateField label="To" value={to} onChange={(value) => { setTo(value); setPage(1); }} /><div className="flex items-end justify-between gap-3 text-xs text-slate-500 lg:col-span-2"><span>Totals and transactions reflect the selected dates and current {scope} view.</span>{!isThisMonth && <button type="button" onClick={resetToThisMonth} className="shrink-0 rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-2 font-semibold text-indigo-700">This month</button>}</div></div></section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 className="font-bold capitalize">{scope} transactions</h2><p className="text-xs text-slate-400">{query.data?.total ?? 0} records</p></div>
      {query.isLoading ? <p className="p-12 text-center text-sm text-slate-500">Loading transactions…</p> : query.isError ? <p className="p-12 text-center text-sm text-rose-600">Transactions could not be loaded.</p> : query.data?.items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b border-slate-100 text-[11px] uppercase tracking-wider text-slate-400"><th className="px-5 py-3">Date</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Supplier / source</th><th className="px-4 py-3">Category</th>{scope === "freelance" && <th className="px-4 py-3">Project / invoice</th>}<th className="px-4 py-3">Note</th><th className="px-5 py-3 text-right">Amount</th><th className="w-14 px-3 py-3" /></tr></thead><tbody>{query.data.items.map((item) => <tr key={item._id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50"><td className="px-5 py-4 text-sm text-slate-500">{formatDate(item.date)}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${item.transactionType === "income" ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{item.transactionType}</span></td><td className="px-4 py-4 text-sm font-semibold text-slate-700">{item.counterparty || "—"}</td><td className="px-4 py-4 text-sm text-slate-500">{item.category || "—"}</td>{scope === "freelance" && <td className="px-4 py-4 text-sm text-slate-500">{item.project || item.invoiceReference || "—"}</td>}<td className="max-w-xs truncate px-4 py-4 text-sm text-slate-500">{item.note || "—"}</td><td className={`px-5 py-4 text-right text-sm font-bold ${item.transactionType === "income" ? "text-emerald-700" : "text-slate-900"}`}>{item.transactionType === "expense" ? "−" : "+"}{money(item.amount)}</td><td className="px-3 py-4"><button type="button" aria-label={`Delete transaction from ${formatDate(item.date)}`} disabled={remove.isPending} onClick={() => { if (window.confirm(`Delete this ${item.transactionType} of ${money(item.amount)}?`)) remove.mutate(item); }} className="grid size-8 place-items-center rounded-lg text-slate-400 hover:bg-rose-50 hover:text-rose-600 disabled:opacity-40"><Trash2 size={15} /></button></td></tr>)}</tbody></table></div> : <div className="grid place-items-center px-6 py-16 text-center"><ReceiptText size={32} className="text-slate-300" /><p className="mt-3 text-sm font-semibold text-slate-700">No transactions in this period</p></div>}
      {query.data && query.data.total > 0 && <div className="flex items-center justify-between border-t border-slate-100 px-5 py-4"><p className="text-xs text-slate-500">Page {query.data.page} of {query.data.pages}</p><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold disabled:opacity-40"><ChevronLeft size={14} />Previous</button><button disabled={page >= query.data.pages} onClick={() => setPage((value) => value + 1)} className="flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold disabled:opacity-40">Next<ChevronRight size={14} /></button></div></div>}
    </section>
    {creating && <TransactionForm scope={scope} categories={query.data?.categories ?? []} onClose={() => setCreating(false)} />}
  </div></CrmShell>;
}

function TransactionForm({ scope, categories, onClose }: { scope: "personal" | "freelance"; categories: string[]; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState({ transactionType: "expense", date: typeof window === "undefined" ? today() : localStorage.getItem(`budget-last-date-${scope}`) || today(), amount: "", counterparty: "", category: scope === "personal" ? "Food" : "Office costs", note: "", project: scope === "freelance" ? "Freelance" : "", invoiceReference: "", hmrcDeductible: false, dwpDeductible: false });
  const [error, setError] = useState("");
  const mutation = useMutation({ mutationFn: (addAnother: boolean) => { void addAnother; return api<BudgetTransaction>("/budget", { method: "POST", body: JSON.stringify({ ...form, scope, amount: Number(form.amount), date: new Date(`${form.date}T12:00:00.000Z`).toISOString(), currency: "GBP" }) }); }, onSuccess: (_saved, addAnother) => { localStorage.setItem(`budget-last-date-${scope}`, form.date); queryClient.invalidateQueries({ queryKey: ["budget"] }); if (addAnother) { setForm((current) => ({ ...current, amount: "", counterparty: "", note: "", project: scope === "freelance" ? "Freelance" : "", invoiceReference: "", hmrcDeductible: false, dwpDeductible: false })); setError(""); } else onClose(); }, onError: (reason) => setError(reason instanceof Error ? reason.message : "Transaction could not be saved") });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const submitter = (event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null; mutation.mutate(submitter?.value === "another"); };
  return <div className="fixed inset-0 z-[140] grid place-items-center overflow-y-auto bg-slate-950/45 p-4"><div role="dialog" aria-modal="true" className="my-8 w-full max-w-2xl rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="text-lg font-bold">Add {scope} transaction</h2><p className="mt-1 text-xs text-slate-500">Record income or an expense in the selected budget.</p></div><button onClick={onClose} aria-label="Close" className="rounded-lg p-2 text-slate-400"><X size={19} /></button></div><form onSubmit={submit} className="p-6"><div className="grid gap-4 sm:grid-cols-2"><Select label="Type" value={form.transactionType} options={["expense", "income"]} onChange={(transactionType) => setForm({ ...form, transactionType })} /><Field label="Date" type="date" value={form.date} onChange={(date) => setForm({ ...form, date })} required /><CounterpartyField scope={scope} label={form.transactionType === "income" ? "Source" : "Supplier"} value={form.counterparty} onChange={(counterparty) => setForm({ ...form, counterparty })} /><Field label="Amount" type="number" value={form.amount} onChange={(amount) => setForm({ ...form, amount })} required /><Select label="Category" value={form.category} options={[...new Set(["Food", ...categories])]} onChange={(category) => setForm({ ...form, category })} />{scope === "freelance" && <><Select label="Project" value={form.project} options={["Freelance", "None", "Handyman"]} onChange={(project) => setForm({ ...form, project })} /><Field label="Invoice reference" value={form.invoiceReference} onChange={(invoiceReference) => setForm({ ...form, invoiceReference })} /><Field label="Note" value={form.note} onChange={(note) => setForm({ ...form, note })} /><Check label="HMRC deductible" checked={form.hmrcDeductible} onChange={(hmrcDeductible) => setForm({ ...form, hmrcDeductible })} /><Check label="DWP deductible" checked={form.dwpDeductible} onChange={(dwpDeductible) => setForm({ ...form, dwpDeductible })} /></>}{scope === "personal" && <Field label="Note" value={form.note} onChange={(note) => setForm({ ...form, note })} />}</div>{error && <p className="mt-4 text-sm text-rose-600">{error}</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Cancel</button><button type="submit" value="another" disabled={mutation.isPending} className="rounded-xl border border-indigo-200 bg-white px-4 py-2.5 text-sm font-semibold text-indigo-700 disabled:opacity-50">Save and add another</button><button type="submit" value="close" disabled={mutation.isPending} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{mutation.isPending ? "Saving…" : "Save"}</button></div></form></div></div>;
}

function CounterpartyField({ scope, label, value, onChange }: { scope: "personal" | "freelance"; label: string; value: string; onChange: (value: string) => void }) {
  const [open, setOpen] = useState(false);
  const search = value.trim();
  const query = useQuery({ queryKey: ["budget-counterparties", scope, search], queryFn: () => api<{ items: { value: string; uses: number }[] }>(`/budget/counterparties?scope=${scope}&search=${encodeURIComponent(search)}&limit=8`), enabled: search.length >= 3, staleTime: 30_000 });
  return <label className="relative"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span><input value={value} autoComplete="off" onFocus={() => setOpen(search.length >= 3)} onBlur={() => window.setTimeout(() => setOpen(false), 150)} onChange={(event) => { onChange(event.target.value); setOpen(event.target.value.trim().length >= 3); }} className="h-11 w-full rounded-xl border border-slate-200 px-3.5 text-sm" />{open && search.length >= 3 && query.data?.items.length ? <div className="absolute z-20 mt-1 w-full overflow-hidden rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl">{query.data.items.map((item) => <button type="button" key={item.value} onMouseDown={(event) => event.preventDefault()} onClick={() => { onChange(item.value); setOpen(false); }} className="flex w-full items-center justify-between rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50"><span className="truncate font-medium">{item.value}</span><span className="ml-3 text-[11px] text-slate-400">{item.uses} uses</span></button>)}</div> : null}</label>;
}

function Stat({ icon: Icon, label, value, tone }: { icon: typeof WalletCards; label: string; value: string; tone: "emerald" | "rose" | "indigo" }) { const colors = { emerald: "bg-emerald-50 text-emerald-600", rose: "bg-rose-50 text-rose-600", indigo: "bg-indigo-50 text-indigo-600" }; return <article className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p></div><div className={`grid size-10 place-items-center rounded-xl ${colors[tone]}`}><Icon size={19} /></div></div></article>; }
function Field({ label, value, onChange, type = "text", required }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span><input type={type} min={type === "number" ? 0 : undefined} step={type === "number" ? "0.01" : undefined} value={value} onChange={(event) => onChange(event.target.value)} required={required} className="h-11 w-full rounded-xl border border-slate-200 px-3.5 text-sm" /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="h-11 w-full rounded-xl border border-slate-200 px-3.5 text-sm capitalize">{options.map((option) => <option key={option} value={option === "None" ? "" : option}>{option}</option>)}</select></label>; }
function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex h-11 items-center gap-2 self-end rounded-xl border border-slate-200 px-3.5 text-sm"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} />{label}</label>; }
function DateField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <Field label={label} type="date" value={value} onChange={onChange} />; }
