"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, LockKeyhole, Save, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { CrmShell } from "../../components/crm-shell";
import { api } from "../../lib/api";
import { FinanceSettings } from "../../lib/crm";

type SettingsResponse = { configured: boolean; settings: FinanceSettings | null; updatedAt?: string };
const defaults: FinanceSettings = { sellerName: "Andras Vargas", tradingName: "", phone: "", email: "", address: "", bankName: "", accountName: "", sortCode: "", accountNumber: "", vatRegistered: false, vatNumber: "", defaultTermsDays: 10, defaultCurrency: "GBP", invoiceFooter: "Thank you for your business. It's a pleasure to work with you." };

export default function SettingsPage() {
  const query = useQuery({ queryKey: ["finance-settings"], queryFn: () => api<SettingsResponse>("/finance-settings"), staleTime: 0 });
  if (query.isLoading) return <CrmShell activePath="/settings"><div className="grid min-h-[60vh] place-items-center text-sm text-slate-500">Loading secure settings…</div></CrmShell>;
  return <FinanceSettingsForm key={query.data?.updatedAt || "new"} initial={query.data?.settings || defaults} />;
}

function FinanceSettingsForm({ initial }: { initial: FinanceSettings }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState<FinanceSettings>(initial);
  const [saved, setSaved] = useState(false);
  const mutation = useMutation({ mutationFn: () => api<SettingsResponse>("/finance-settings", { method: "PUT", body: JSON.stringify(form) }), onSuccess: (data) => { queryClient.setQueryData(["finance-settings"], data); setSaved(true); window.setTimeout(() => setSaved(false), 2500); } });
  const submit = (event: FormEvent) => { event.preventDefault(); mutation.mutate(); };
  return <CrmShell activePath="/settings"><div className="mx-auto max-w-[1100px] px-4 py-7 md:px-8 md:py-9"><div><p className="text-sm font-semibold text-indigo-600">Workspace settings</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Finance settings</h1><p className="mt-2 text-sm text-slate-500">Seller identity, invoice defaults, and private payment instructions.</p></div>
    <div className="mt-7 flex items-start gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><ShieldCheck className="mt-0.5 shrink-0 text-emerald-600" size={20} /><div><p className="text-sm font-bold text-emerald-900">Encrypted and local</p><p className="mt-1 text-xs leading-5 text-emerald-700">These values are encrypted before being stored in MongoDB. The encryption key stays in a local, Git-ignored file and is never returned by the API.</p></div></div>
    <form onSubmit={submit} className="mt-5 space-y-5"><Section title="Seller details" description="Shown at the top of generated invoices."><div className="grid gap-4 sm:grid-cols-2"><Field label="Legal name" value={form.sellerName} onChange={(sellerName) => setForm({ ...form, sellerName })} required /><Field label="Trading name" value={form.tradingName || ""} onChange={(tradingName) => setForm({ ...form, tradingName })} /><Field label="Phone" value={form.phone || ""} onChange={(phone) => setForm({ ...form, phone })} /><Field label="Email" type="email" value={form.email || ""} onChange={(email) => setForm({ ...form, email })} /><label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-semibold text-slate-600">Address</span><textarea rows={4} value={form.address || ""} onChange={(event) => setForm({ ...form, address: event.target.value })} className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-indigo-300 focus:ring-4 focus:ring-indigo-100" /></label></div></Section>
      <Section title="Payment details" description="Printed only on invoices generated from this local CRM."><div className="grid gap-4 sm:grid-cols-2"><Field label="Bank name" value={form.bankName || ""} onChange={(bankName) => setForm({ ...form, bankName })} /><Field label="Account name" value={form.accountName || ""} onChange={(accountName) => setForm({ ...form, accountName })} /><Field label="Sort code" value={form.sortCode || ""} onChange={(sortCode) => setForm({ ...form, sortCode })} /><Field label="Account number" value={form.accountNumber || ""} onChange={(accountNumber) => setForm({ ...form, accountNumber })} /></div></Section>
      <Section title="Invoice defaults" description="Used as starting values for new invoices."><div className="grid gap-4 sm:grid-cols-3"><Field label="Payment terms (days)" type="number" value={String(form.defaultTermsDays)} onChange={(value) => setForm({ ...form, defaultTermsDays: Number(value) })} /><Field label="Currency" value={form.defaultCurrency} onChange={(defaultCurrency) => setForm({ ...form, defaultCurrency: defaultCurrency.toUpperCase().slice(0, 3) })} /><label className="flex items-end"><span className="flex h-11 w-full items-center gap-3 rounded-xl border border-slate-200 px-3.5 text-sm font-semibold text-slate-700"><input type="checkbox" checked={form.vatRegistered} onChange={(event) => setForm({ ...form, vatRegistered: event.target.checked })} className="size-4 accent-indigo-600" />VAT registered</span></label>{form.vatRegistered && <Field label="VAT number" value={form.vatNumber || ""} onChange={(vatNumber) => setForm({ ...form, vatNumber })} />}<label className="sm:col-span-3"><span className="mb-1.5 block text-xs font-semibold text-slate-600">Invoice footer</span><textarea rows={3} value={form.invoiceFooter || ""} onChange={(event) => setForm({ ...form, invoiceFooter: event.target.value })} className="w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-indigo-300 focus:ring-4 focus:ring-indigo-100" /></label></div></Section>
      {mutation.isError && <p className="text-sm text-rose-600">{mutation.error instanceof Error ? mutation.error.message : "Settings could not be saved"}</p>}<div className="flex justify-end"><button disabled={mutation.isPending} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saved ? <CheckCircle2 size={17} /> : <Save size={17} />}{saved ? "Saved securely" : mutation.isPending ? "Encrypting…" : "Save finance settings"}</button></div>
    </form><div className="mt-5 flex items-center gap-2 text-xs text-slate-400"><LockKeyhole size={14} />Keep the local encryption key backed up separately. Losing it makes the encrypted settings unrecoverable.</div>
  </div></CrmShell>;
}

function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 md:p-6"><div className="mb-5"><h2 className="font-bold text-slate-950">{title}</h2><p className="mt-1 text-xs text-slate-500">{description}</p></div>{children}</section>; }
function Field({ label, value, onChange, type = "text", required }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} required={required} min={type === "number" ? 0 : undefined} className="h-11 w-full rounded-xl border border-slate-200 px-3.5 text-sm outline-none focus:border-indigo-300 focus:ring-4 focus:ring-indigo-100" /></label>; }
