"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CheckCircle2, Printer, Send, XCircle } from "lucide-react";
import { useParams } from "next/navigation";
import { CrmShell } from "../../../components/crm-shell";
import { SafeLink as Link } from "../../../components/safe-link";
import { api } from "../../../lib/api";
import { FinanceSettings, Invoice, formatDate } from "../../../lib/crm";

const money = (value: number, currency: string) => new Intl.NumberFormat("en-GB", { style: "currency", currency }).format(value || 0);

export default function InvoiceDetailPage() {
  const { id } = useParams<{ id: string }>();
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["invoice", id], queryFn: () => api<Invoice>(`/invoices/${id}`) });
  const settingsQuery = useQuery({ queryKey: ["finance-settings"], queryFn: () => api<{ configured: boolean; settings: FinanceSettings | null }>("/finance-settings") });
  const mutation = useMutation({ mutationFn: (status: Invoice["status"]) => api<Invoice>(`/invoices/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }), onSuccess: (invoice) => { queryClient.setQueryData(["invoice", id], invoice); queryClient.invalidateQueries({ queryKey: ["invoices"] }); } });
  const invoice = query.data;
  const settings = settingsQuery.data?.settings;
  if (query.isLoading) return <CrmShell activePath="/invoices"><div className="grid min-h-[60vh] place-items-center text-sm text-slate-500">Loading invoice…</div></CrmShell>;
  if (!invoice) return <CrmShell activePath="/invoices"><div className="grid min-h-[60vh] place-items-center text-center"><div><h1 className="text-xl font-bold">Invoice not found</h1><Link href="/invoices" className="mt-3 inline-block text-sm font-semibold text-indigo-600">Return to invoices</Link></div></div></CrmShell>;
  return <CrmShell activePath="/invoices"><div className="mx-auto max-w-[1100px] px-4 py-7 md:px-8 md:py-9 print:max-w-none print:p-0">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3 print:hidden"><Link href="/invoices" className="flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-indigo-600"><ArrowLeft size={16} />Invoices</Link><div className="flex flex-wrap gap-2">{invoice.status === "draft" && <Action icon={Send} label="Mark sent" onClick={() => mutation.mutate("sent")} />}{invoice.status !== "paid" && invoice.status !== "void" && <Action icon={CheckCircle2} label="Mark paid" onClick={() => mutation.mutate("paid")} primary />}{invoice.status !== "void" && <Action icon={XCircle} label="Void" onClick={() => mutation.mutate("void")} />}<Action icon={Printer} label="Print / PDF" onClick={() => window.print()} /></div></div>
    <article className="min-h-[900px] rounded-2xl border border-slate-200 bg-white p-7 shadow-sm md:p-12 print:min-h-0 print:rounded-none print:border-0 print:p-8 print:shadow-none">
      <header className="flex flex-col justify-between gap-8 border-b-4 border-amber-500 pb-6 sm:flex-row"><div><p className="text-3xl font-black tracking-tight text-slate-950">AV</p><p className="mt-1 text-sm font-semibold text-slate-700">{settings?.tradingName || settings?.sellerName || "Andras Vargas"}</p>{settings?.phone && <p className="mt-2 text-xs text-slate-500">{settings.phone}</p>}{settings?.email && <p className="mt-1 text-xs text-slate-500">{settings.email}</p>}{settings?.address && <p className="mt-1 whitespace-pre-line text-xs leading-5 text-slate-500">{settings.address}</p>}</div><div className="sm:text-right"><p className="text-3xl font-light uppercase tracking-[.25em] text-rose-950">Invoice</p><p className="mt-3 text-sm font-bold text-slate-900">#{invoice.number}</p><p className="mt-1 text-xs text-slate-500">Status: <span className="font-bold uppercase">{invoice.status}</span></p></div></header>
      <section className="mt-8 grid gap-8 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Issued to</p><p className="mt-2 text-base font-bold text-slate-950">{invoice.customerName}</p>{invoice.customerContact && <p className="mt-1 text-sm text-slate-600">{invoice.customerContact}</p>}{invoice.billingAddress && <p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-500">{invoice.billingAddress}</p>}</div><dl className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm sm:justify-self-end"><dt className="text-slate-400">Issue date</dt><dd className="text-right font-semibold">{formatDate(invoice.issueDate)}</dd><dt className="text-slate-400">Supply date</dt><dd className="text-right font-semibold">{formatDate(invoice.supplyDate)}</dd><dt className="text-slate-400">Due date</dt><dd className="text-right font-semibold">{formatDate(invoice.dueDate)}</dd><dt className="text-slate-400">Terms</dt><dd className="text-right font-semibold">{invoice.terms || "—"}</dd></dl></section>
      {(invoice.project || invoice.purchaseOrder) && <section className="mt-8 grid gap-3 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-2">{invoice.project && <p><span className="text-slate-400">Project:</span> <span className="font-semibold">{invoice.project}</span></p>}{invoice.purchaseOrder && <p><span className="text-slate-400">P.O. number:</span> <span className="font-semibold">{invoice.purchaseOrder}</span></p>}</section>}
      {(settings?.bankName || settings?.accountNumber) && <section className="mt-6 ml-auto max-w-md rounded-xl border border-slate-200 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Payment details</p><dl className="mt-3 grid grid-cols-2 gap-x-4 gap-y-2 text-sm">{settings.bankName && <><dt className="text-slate-400">Bank</dt><dd className="text-right font-semibold">{settings.bankName}</dd></>}{settings.accountName && <><dt className="text-slate-400">Account name</dt><dd className="text-right font-semibold">{settings.accountName}</dd></>}{settings.sortCode && <><dt className="text-slate-400">Sort code</dt><dd className="text-right font-semibold">{settings.sortCode}</dd></>}{settings.accountNumber && <><dt className="text-slate-400">Account number</dt><dd className="text-right font-semibold">{settings.accountNumber}</dd></>}</dl></section>}
      <div className="mt-8 overflow-hidden rounded-xl border border-slate-200"><table className="w-full text-left"><thead className="bg-rose-950 text-xs uppercase tracking-wider text-white"><tr><th className="px-4 py-3">Description</th><th className="px-4 py-3 text-right">Quantity</th><th className="px-4 py-3">Unit</th><th className="px-4 py-3 text-right">Rate</th><th className="px-4 py-3 text-right">Amount</th></tr></thead><tbody>{invoice.lineItems.map((item) => <tr key={item._id || item.description} className="border-b border-slate-100 last:border-0"><td className="px-4 py-4 text-sm text-slate-700">{item.description}</td><td className="px-4 py-4 text-right text-sm">{item.quantity}</td><td className="px-4 py-4 text-sm capitalize text-slate-500">{item.unit || "—"}</td><td className="px-4 py-4 text-right text-sm">{money(item.rate, invoice.currency)}</td><td className="px-4 py-4 text-right text-sm font-semibold">{money(item.amount ?? item.quantity * item.rate, invoice.currency)}</td></tr>)}</tbody></table></div>
      <section className="mt-6 ml-auto max-w-sm space-y-2 text-sm"><div className="flex justify-between"><span className="text-slate-500">Subtotal</span><span>{money(invoice.subtotal, invoice.currency)}</span></div><div className="flex justify-between"><span className="text-slate-500">Credit</span><span>− {money(invoice.credit, invoice.currency)}</span></div><div className="flex justify-between"><span className="text-slate-500">VAT ({invoice.vatRate}%)</span><span>{money(invoice.vatAmount, invoice.currency)}</span></div><div className="flex justify-between border-t-2 border-slate-900 pt-3 text-lg font-bold"><span>Total amount due</span><span>{money(invoice.total, invoice.currency)}</span></div></section>
      {invoice.note && <section className="mt-10 border-t border-slate-100 pt-6"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Notes</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{invoice.note}</p></section>}
      <footer className="mt-16 text-sm text-slate-500"><p>{settings?.invoiceFooter || "Thank you for your business. It's a pleasure to work with you."}</p><p className="mt-5">Kind regards,</p><p className="mt-4 font-semibold text-slate-700">{settings?.sellerName || "Andras V."}</p>{!settings && <p className="mt-8 text-xs text-amber-600 print:hidden">Add encrypted seller and payment details in Settings before issuing this invoice.</p>}</footer>
    </article>
  </div></CrmShell>;
}

function Action({ icon: Icon, label, onClick, primary }: { icon: typeof Send; label: string; onClick: () => void; primary?: boolean }) { return <button onClick={onClick} className={`flex items-center gap-2 rounded-xl px-3.5 py-2.5 text-sm font-semibold ${primary ? "bg-indigo-600 text-white" : "border border-slate-200 bg-white text-slate-700"}`}><Icon size={16} />{label}</button>; }
